'''
This file handles solving each problem based on the type of bounds
This file is outdated and has error handling that is no longer needed and not well implemented
3/25 - had AI rewrite and get rid of extra information

Each method returns an array:
    [successes, starts, objvalue, times, iterations, messages]

This array is used for the writer.
'''
import os
import time
import shutil
import pycutest
import numpy as np
from scipy.optimize import minimize, NonlinearConstraint, Bounds


class solver:
    def __init__(self, name):
        #store the problem inforation in p
        self.p = pycutest.import_problem(name)
        self.name = name
        #initial guess from the cutest
        self.x0 = self.p.x0
        self.pbounds = list(zip(self.p.bl, self.p.bu))

    def _random_starts(self, k=3):
        #cutoff for infinity
        inf_cut = 1e19
        #Scaled version of max is used for infinite variables
        maximum = 1e3
        #this creates a random number generator
        rng = np.random.default_rng()

        #converts the cutest arrays to numpy arrays
        bl = np.asarray(self.p.bl, dtype=float)
        bu = np.asarray(self.p.bu, dtype=float)
        x0 = np.asarray(self.x0, dtype=float)

        #Convert huge numbers to numpy infinities
        bl = np.where(bl < -inf_cut, -np.inf, bl)
        bu = np.where(bu > inf_cut, np.inf, bu)

        #This gets the largest absolute value from x0 uses it as a scale for the maximum and minimum
        scale = max(1.0, np.linalg.norm(x0, ord=np.inf))
        maximum = maximum * scale

        #replace infinite values in bl and bu with the maximum/minimum caps
        #otherwise keep them as bl or bu respectively
        lo = np.where(np.isfinite(bl), bl, -maximum)
        hi = np.where(np.isfinite(bu), bu, maximum)

        starts = []
        for _ in range(k):
            '''
            we take a random vector generated by () and add it to x0
            '''
            x = x0 + (.1 * scale * rng.standard_normal(size=x0.size))
            '''
            this goes index by index and makes sure the low values
            are are above the boundary and the high values are below the boundary
            if they fail then replace with the boundary
            '''
            x = np.minimum(np.maximum(x, lo), hi)
            starts.append(x)

        return starts

    #random starts for type 2 problems
    def _random_starts_t2(self, k=3):
        rng = np.random.default_rng()

        p = self.p

        #converts the cutest arrays to numpy arrays
        x0 = np.asarray(p.x0, dtype=float)
        bl = np.asarray(p.bl, dtype=float)
        bu = np.asarray(p.bu, dtype=float)

        #set the infinite bounds correctly using numpy
        lb = np.where(bl <= -1e19, -np.inf, bl)
        ub = np.where(bu >= 1e19, np.inf, bu)

        #make sure the initial point is within the bounds
        x0 = np.clip(x0, lb, ub)

        scale = max(1.0, np.linalg.norm(x0, ord=np.inf))
        step0 = 0.1 * scale

        starts = []
        for _ in range(k):
            x = None
            best = None
            best_violation = np.inf
            step = step0

            for j in range(200):
                cand = x0 + step * rng.standard_normal(size=x0.size)
                cand = np.clip(cand, lb, ub)

                try:
                    c = p.cons(cand)

                    #compute constraint violation
                    low_v = np.maximum(p.cl - c, 0)
                    high_v = np.maximum(c - p.cu, 0)
                    violation = np.max(low_v) + np.max(high_v)

                    if violation < best_violation:
                        best_violation = violation
                        best = cand

                    if violation == 0:
                        x = cand
                        break

                except Exception:
                    pass

                #shrink step slowly if we keep missing feasibility
                if j % 40 == 39:
                    step *= 0.5

            #if no feasible point found use least infeasible
            if x is None:
                x = best if best is not None else x0

            starts.append(x)

        return starts

    #store the function and gradient/jacobian required for solve methods
    def fun(self, x):
        return self.p.obj(x)

    def jac(self, x):
        return self.p.obj(x, gradient=True)[1]

    def simple_bounds(self, method):
        #This is a check to make my mac not crash :(
        n = self.p.n
        if n > 3000:
            print(f"Skipping {self.name}: too large for {method} (n={n})\n")
            return [None, 0.0, None, None]

        #start timer so it has full function scope
        start = time.perf_counter()

        #this is called every callback by the solver so every set amount of iterations to check time
        def timeout(xk):
            if time.perf_counter() - start > 60 * 20:
                raise TimeoutError

        starts = self._random_starts(k=3)

        print(f"Method: {method}")
        print(f"Problem: {self.name}")

        run_id = 1
        objvalue = []
        times = []
        successes = []
        iterations = []
        messages = []

        for x0_try in starts:
            try:
                #start the timer again so it is more accurate
                start = time.perf_counter()
                print(f"\nRun {run_id}")
                run_id += 1

                if method == "Powell" or method == "Nelder-Mead":
                    res = minimize(self.fun, x0_try, method=method, bounds=self.pbounds, callback=timeout)
                elif method == "TNC":
                    #TNC takes Conjugate-Gradient
                    res = minimize(self.fun, x0_try, jac=self.jac, method=method, bounds=self.pbounds, callback=timeout)
                else:
                    res = minimize(self.fun, x0_try, jac=self.jac, method=method, bounds=self.pbounds, callback=timeout)

                #timer doesnt start at 0 so subtract it out
                total = time.perf_counter() - start
                print(f"Starting point: {x0_try}")
                print(f"Time: {total}")
                print(f"Success: {res.success}")
                print(f"Message: {res.message}")

                objvalue.append(res.fun)
                times.append(total)
                if res.success:
                    successes.append("success")
                else:
                    successes.append("fail")
                iterations.append(getattr(res, "nit", None))
                messages.append(res.message)

            except Exception as e:
                objvalue.append(float("nan"))
                successes.append("fail")
                times.append(float("nan"))
                iterations.append(None)
                messages.append(str(e))

        return [successes, starts, objvalue, times, iterations, messages]

    def complex_bounds(self, method):
        #set the timeout to 20 minutes
        def timeout(xk, state=None):
            if time.perf_counter() - start > 60 * 20:
                raise TimeoutError

        starts = self._random_starts_t2(3)

        print(f"Method: {method}")
        print(f"Problem: {self.name}")

        #needed for trust-constr
        bl = np.asarray(self.p.bl, dtype=float)
        bu = np.asarray(self.p.bu, dtype=float)
        bounds = Bounds(bl, bu, keep_feasible=True)

        #this whole next block is for constraint functions
        def cons_func(x):
            return self.p.cons(x)

        #the jacobians have non-finite values which causes trust-constr to error so the block of code below is prevention
        useful_jac = self.jac
        try:
            if not np.all(np.isfinite(self.jac(self.x0))):
                useful_jac = None
        except Exception:
            useful_jac = None

        #scipy classes anything other than box bounds as nonlinear
        nonlinear_cons = NonlinearConstraint(fun=cons_func, lb=self.p.cl, ub=self.p.cu)
        cons = [nonlinear_cons]

        run_id = 1
        objvalue = []
        times = []
        successes = []
        iterations = []
        messages = []

        #start timer
        for x0 in starts:
            try:
                start = time.perf_counter()

                #scale sensitive parameters like trust-region radii should reflect
                #the geometry of the variables, not their raw units.
                scale = np.maximum(1.0, np.abs(x0))

                #For bounded variables, box width is often the natural scale.
                finite = np.isfinite(bl) & np.isfinite(bu)
                scale[finite] = np.maximum(scale[finite], np.maximum(1.0, bu[finite] - bl[finite]))

                #This does not solve the problem in scaled coordinates. It only uses
                #scaled_x0 to choose a more meaningful initial radius for trust-region methods.
                scaled_x0 = x0 / scale
                r0 = min(1.0, max(0.1, np.linalg.norm(scaled_x0, ord=np.inf)))

                if method == "trust-constr":
                    #add scale based parameter tuning
                    res = minimize(
                        self.fun,
                        x0,
                        jac=useful_jac,
                        method=method,
                        bounds=bounds,
                        constraints=cons,
                        callback=timeout,
                        options={
                            "initial_tr_radius": r0,
                        }
                    )
                elif method == "COBYLA":
                    #COBYLA uses rhobeg as an initial step size, so it should be
                    #interpreted in scaled coordinates as well.
                    res = minimize(
                        self.fun,
                        x0,
                        method=method,
                        constraints=cons,
                        callback=timeout,
                        options={
                            "rhobeg": 0.5 * np.mean(scale),
                        }
                    )
                else:
                    res = minimize(
                        self.fun,
                        x0,
                        jac=useful_jac,
                        method=method,
                        bounds=bounds,
                        constraints=cons,
                        callback=timeout,
                    )

                #timer doesnt start at 0 so subtract it out
                total = time.perf_counter() - start
                print(f"Run {run_id}")
                run_id += 1
                print(f"Time: {total:.2f}")
                print(f"Success: {res.success}")
                print(f"Message: {res.message}")

                objvalue.append(res.fun)
                times.append(total)

                if res.success:
                    successes.append("success")
                else:
                    successes.append("fail")

                iterations.append(getattr(res, "nit", None))
                messages.append(res.message)

            except Exception as e:
                objvalue.append(float("nan"))
                successes.append("fail")
                times.append(float("nan"))
                iterations.append(None)
                messages.append(str(e))

        return [successes, starts, objvalue, times, iterations, messages]

    #should be done
    def unbounded(self, method):
        #This is a check to make my mac not crash :(
        n = self.p.n
        if n > 3000:
            print(f"Skipping {self.name}: too large for {method} (n={n})\n")
            return [None, 0.0, None, None]

        #start timer so it has full function scope
        start = time.perf_counter()

        #this is called every callback by the solver so every set amount of iterations to check time
        def timeout(xk):
            if time.perf_counter() - start > 20 * 60:
                raise TimeoutError

        def hess(x):
            return self.p.hess(x)

        def hessp(x, p):
            return self.p.hprod(x, p)

        starts = self._random_starts(3)

        print("Method: " + method)
        print("Problem: " + str(self.name))
        print(f"Dimension: {self.p.n}")

        objvalue = []
        times = []
        successes = []
        iterations = []
        messages = []

        run_id = 1
        for x0 in starts:
            try:
                start = time.perf_counter()
                print(f"\nRun {run_id}")
                run_id += 1

                #scale sensitive parameters like trust-region radii should reflect
                #the geometry of the variables not their raw units.
                scale = np.maximum(1.0, np.abs(x0))

                #This does not solve the problem in scaled coordinates it only uses
                #scaled_x0 to choose a more meaningful initial radius for trust-region methods.
                scaled_x0 = x0 / scale
                r0 = min(1.0, max(0.1, np.linalg.norm(scaled_x0, ord=np.inf)))

                if method == "trust-ncg":
                    res = minimize(
                        self.fun,
                        x0,
                        jac=self.jac,
                        hessp=hessp,
                        method=method,
                        callback=timeout,
                        options={
                            "initial_trust_radius": r0,
                        }
                    )
                elif method == "dogleg":
                    res = minimize(
                        self.fun,
                        x0,
                        jac=self.jac,
                        hess=hess,
                        method=method,
                        callback=timeout,
                        options={
                            "initial_trust_radius": r0,
                            "max_trust_radius": max(10.0, 10.0 * r0),
                        }
                    )
                else:
                    res = minimize(self.fun, x0, jac=self.jac, method=method, callback=timeout)

                #timer doesnt start at 0 so subtract it out
                total = time.perf_counter() - start
                print(f"Time: {total:.2f}")
                print(f"Success: {res.success}")
                print(f"Message: {res.message}")

                objvalue.append(res.fun)
                times.append(total)
                if res.success:
                    successes.append("success")
                else:
                    successes.append("fail")
                iterations.append(getattr(res, "nit", None))
                messages.append(res.message)

            except Exception as e:
                objvalue.append(float("nan"))
                successes.append("fail")
                times.append(float("nan"))
                iterations.append(None)
                messages.append(str(e))

        return [successes, starts, objvalue, times, iterations, messages]


def clearcache():
    cache = os.path.expanduser("~/.pycutest_cache")
    shutil.rmtree(cache, ignore_errors=True)
    os.makedirs(cache, exist_ok=True)